#get the data generated by java_weka and make a matrix for further clustering

types = [('auxo','AUX'),('both','CE'),('rich','RICH')]
 
for t in types:
	saida = open('weka/'+t[0]+'/matrix.csv','w')
	listas = []
	for i in range(1,101):
		f = open('weka/'+t[0]+'/out_java_'+t[1]+'/'+str(i)+'.out')
		l = []
		for line in f:
			l.append(line[74:79])
		listas.append(l)

	primer="inst1"
	for j in range(len(listas[0])-1):
		primer = primer+",inst"+str(j+2)

	saida.write(primer+"\n")

	for elem in listas:
		line = ','.join([str(x) for x in elem])
		saida.write(line+"\n")

